### ISSUE TITLE
Form data

### ISSUE THREAD

**Issue by djjudas21** [bentasker/Ecowitt_to_InfluxDB#1]
Hey, hope you don't mind me contacting you. I'm writing something very similar for my Ecowitt weather station, except mine is a Prometheus exporter as I don't currently use InfluxDB.

I'm also using Python/Flask to receive the POST data from the Ecowitt but I'm having some really weird issues with the `request` object and the way Flask parses out the `request.form` data.

Like you, I initially tried to access the POST data with:

```py
data = request.form
for key in data:
    value = data[key]
```

which worked absolutely fine for my "faked" data submitted using `curl` but was empty for real data from the Ecowitt. A packet dump shows all the form data is present and correct, just that Flask doesn't seem to access it.

I also tried access the raw HTTP body and parsing it out manually like the [Ecowither](https://github.com/pa3hcm/ecowither) project does

```py
for field in request.get_data(as_text=True).split('&'):
    [key, value] = field.split('=')
```

and this worked with my simulated `curl` data but was also empty with real Ecowitt data.

So it's the Ecowitt data that seems to be the problem, but like I say, it looks fine when I dump it

```json
{
    "path": "/report",
    "headers": {
        "host": "192.168.0.65",
        "connection": "Close",
        "content-type": "application/x-www-form-urlencoded",
        "content-length": "493"
    },
    "method": "POST",
    "body": "PASSKEY=573AF40DB42C66057D20631F706CD585&stationtype=EasyWeatherPro_V5.1.1&runtime=1&dateutc=2023-06-20+14:56:02&tempinf=73.4&humidityin=49&baromrelin=29.917&baromabsin=29.536&tempf=72.5&humidity=58&winddir=251&windspeedmph=1.12&windgustmph=2.24&maxdailygust=9.17&solarradiation=293.99&uv=2&rainratein=0.000&eventrainin=0.638&hourlyrainin=0.000&dailyrainin=0.638&weeklyrainin=0.650&monthlyrainin=0.650&yearlyrainin=0.650&totalrainin=0.650&wh65batt=0&freq=868M&model=WS2900_V2.01.18&interval=60",
    "fresh": false,
    "hostname": "192.168.0.65",
    "ip": "::ffff:10.1.199.64",
    "ips": [],
    "protocol": "http",
    "query": {},
    "subdomains": [],
    "xhr": false,
    "os": {
        "hostname": "http-webhook-6675856576-j2jzb"
    },
    "connection": {}
}
```

Tearing my hair out here., Wondering if it's some kind of problem with Flask where it's refusing to parse out the form data because the headers are wrong or something. Did you have any issues with this?

Thanks

**Comment by bentasker** [comment]
Hey,

This is not something I ran into I'm afraid.

> I also tried access the raw HTTP body and parsing it out manually like the [Ecowither](https://github.com/pa3hcm/ecowither) project does

Now that's interesting, because it should totally work.

If just before your `for` loop you drop in 

```python
print(request.get_data(as_text=True))
```
Does it print the line.

If so, I'd be inclined to start looking at charsets and the like. I'm wondering if the `&` and `=` you're splitting on have ended up being unicode (or perhaps are unicode in the submission).

**Comment by djjudas21** [comment]
> If just before your `for` loop you drop in
> 
> ```python
> print(request.get_data(as_text=True))
> ```
> 
> Does it print the line.

No, it prints an empty string. So I'm wondering if there's a bug in the version of Flask I'm using (2.3.2, the latest) but I can't find anything to corroborate that. I guess I'll write up a bug report for them and try other versions of Flask while I'm waiting.

**Comment by bentasker** [comment]
How weird... I remember years (and years) back, I ran into an issue in PHP where post data just wouldn't be there (it wasn't handling encoded carriage returns IIRC), so it's not unheard of for weird shit to happen.

Is anything higher in your call chain parsing the form data? the docs for `get_data` note:

> Note that if the form data was already parsed this method will not return anything as form data parsing does not cache the data like this method does. 

The doc [is a little unclear](https://tedboy.github.io/flask/generated/generated/flask.Request.get_data.html) whether its referring to calling it with `parse_form_data` or parsing elsewhere in `request`

Maybe stick that `print()` at the top of the method and see what you get - just in case something's consuming the data (wouldn't explain `curl` working though).

My ecowitt comes in via my Nginx reverse proxy, I wonder if that's why I didn't encounter this? Maybe stand up a docker container to put Nginx in front and see if the behaviour changes (although, like you, I don't see anything wrong with the dump of the request)

**Comment by djjudas21** [comment]
Yes I read about the way that some of the methods can cause change of behaviour in other methods when it comes to decoding form data. There's nothing else in my project that handles the request, and I tried putting the `print()` right at the top and it was still the same.

I'm running this in Kubernetes and it's currently just using a Service to expose port 8080 on my LAN. I can front it with an Ingress (which is just Nginx) so it will get proxied.

**Comment by djjudas21** [comment]
FYI I've logged a bug against Flask, just in case you're interested in following along: https://github.com/pallets/flask/issues/5168

Thanks for your help & advice on this, I'll close this issue now. Have a nice evening :+1:

**Comment by bentasker** [comment]
No worries, have a goodun

**Comment by djjudas21** [comment]
Solved it. It was a combination of two bugs. Firstly the specific firmware version I'm running on my Ecowitt (v5.1.1) has a bug and misses a space in one of the HTTP headers. Secondly, Flask doesn't seem to catch this and fails to parse the POST data but otherwise seems happy to accept the request. The maintainer isn't keen on fixing this behaviour because the root cause lies with the Ecowitt, not with Flask. But every other HTTP server seems to cope fine with it.

https://github.com/pallets/werkzeug/issues/2734

Happily, using an NGINX reverse proxy (in my case, a Kubernetes Ingress) with no special config fixes the dodgy header in flight and it "just works".

**Comment by bentasker** [comment]
Thanks for the update, that's interesting

> The maintainer isn't keen on fixing this behaviour because the root cause lies with the Ecowitt, not with Flask

No, if that is the cause, the issue lies with Flask.

Both of the following are legal and equivalent
```
cache-control:no-cache
cache-control: no-cache
```

RFC 7230 [defines a header](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2) as

> Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.

Section 3.2.4 is equally explicit

> A field value might be preceded and/or followed by optional
   whitespace (OWS); a single SP preceding the field-value is preferred
   for consistent readability by humans.  The field value does not
   include any leading or trailing whitespace: OWS occurring before the
   first non-whitespace octet of the field value or after the last
   non-whitespace octet of the field value ought to be excluded by
   parsers when extracting the field value from a header field.

If Flask is not treating the leading space as optional then it's not RFC compliant and should probably be treated as a bug.
